const SELECT_PAGE = 'SELECT_PAGE';

const FETCH_PLAYERS = 'FETCH_PLAYERS';
const ADD_PLAYER = 'ADD_PLAYER';
const UPDATE_PLAYER = 'UPDATE_PLAYER';
const REMOVE_PLAYER = 'REMOVE_PLAYER';

const CREATE_ROSTER = 'CREATE_ROSTER';
const FETCH_ROSTERS = 'FETCH_ROSTERS';

const PENDING = 'PENDING';
const FULFILLED = 'FULFILLED';
const REJECTED = 'REJECTED';

export default {
    SELECT_PAGE,
    FETCH_PLAYERS,
    ADD_PLAYER,
    UPDATE_PLAYER,
    REMOVE_PLAYER,
    CREATE_ROSTER,
    FETCH_ROSTERS,
    PENDING,
    FULFILLED,
    REJECTED
}