const SELECT_PAGE = 'SELECT_PAGE';
const CREATE_ROSTER = 'CREATE_ROSTER';
const MANAGE_ROSTERS = 'MANAGE_ROSTERS';
const SET_LINEUPS = 'SET_LINEUPS';

const FETCH_PLAYERS = 'FETCH_PLAYERS';
const ADD_PLAYER = 'ADD_PLAYER';
const UPDATE_PLAYER = 'UPDATE_PLAYER';
const REMOVE_PLAYER = 'REMOVE_PLAYER';

const FETCH_ROSTERS = 'FETCH_ROSTERS';
const DISPLAY_ROSTER_MODAL = 'DISPLAY_ROSTER_MODAL';

const PENDING = 'PENDING';
const FULFILLED = 'FULFILLED';
const REJECTED = 'REJECTED';

export default {
    SELECT_PAGE,
    CREATE_ROSTER,
    MANAGE_ROSTERS,
    SET_LINEUPS,
    FETCH_PLAYERS,
    ADD_PLAYER,
    UPDATE_PLAYER,
    REMOVE_PLAYER,
    FETCH_ROSTERS,
    DISPLAY_ROSTER_MODAL,
    PENDING,
    FULFILLED,
    REJECTED
}